from __future__ import annotations

import hashlib
from functools import lru_cache
from pathlib import Path
from typing import Any

import chromadb
from sentence_transformers import SentenceTransformer


PROJECT_ROOT = Path(__file__).resolve().parent.parent
VECTOR_DB_PATH = PROJECT_ROOT / "vector_db"
MODELS_DIR = PROJECT_ROOT / "models"

BASE_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"


def create_text_id(prefix: str, text: str) -> str:
    """
    Generate a stable ID from document text.

    The same text receives the same ID, so Chroma upsert() updates
    the existing record instead of creating duplicates.
    """
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:20]
    return f"{prefix}_{digest}"


def clean_metadata(metadata: dict[str, Any] | None) -> dict[str, Any]:
    """
    Chroma metadata values should be simple scalar types.
    Remove None values and convert unsupported values to strings.
    """
    if not metadata:
        return {}

    cleaned: dict[str, Any] = {}

    for key, value in metadata.items():
        if value is None:
            continue

        if isinstance(value, (str, int, float, bool)):
            cleaned[key] = value
        else:
            cleaned[key] = str(value)

    return cleaned


@lru_cache(maxsize=3)
def load_embedding_model(model_type: str) -> SentenceTransformer:
    """
    Load one of the three embedding models and cache it.

    model_type:
        generic -> pretrained MiniLM
        full    -> fully fine-tuned model
        lora    -> LoRA/PEFT model
    """
    if model_type == "generic":
        model_path: str | Path = BASE_MODEL_NAME

    elif model_type == "full":
        model_path = MODELS_DIR / "resume_jd_matcher"

    elif model_type == "lora":
        model_path = MODELS_DIR / "resume_jd_matcher_lora"

    else:
        raise ValueError(
            "model_type must be 'generic', 'full', or 'lora'."
        )

    if isinstance(model_path, Path):
        if not model_path.exists():
            raise FileNotFoundError(
                f"Model directory was not found: {model_path}"
            )

    print(f"Loading {model_type} embedding model from: {model_path}")
    return SentenceTransformer(str(model_path))


class ResumeVectorStore:
    """
    Local ChromaDB store for resume and job-description embeddings.

    A separate collection is used for each model because embeddings
    generated by different models should not be mixed.
    """

    def __init__(self, model_type: str = "full") -> None:
        if model_type not in {"generic", "full", "lora"}:
            raise ValueError(
                "model_type must be 'generic', 'full', or 'lora'."
            )

        self.model_type = model_type
        self.model = load_embedding_model(model_type)

        VECTOR_DB_PATH.mkdir(parents=True, exist_ok=True)

        self.client = chromadb.PersistentClient(
            path=str(VECTOR_DB_PATH)
        )

        self.resume_collection = self.client.get_or_create_collection(
            name=f"resumes_{model_type}"
        )

        self.job_collection = self.client.get_or_create_collection(
            name=f"jobs_{model_type}"
        )

    def embed(self, text: str) -> list[float]:
        """
        Convert text to one normalized embedding.
        """
        if not text or not text.strip():
            raise ValueError("Cannot create an embedding from empty text.")

        embedding = self.model.encode(
            text,
            normalize_embeddings=True,
            convert_to_numpy=True
        )

        return embedding.tolist()

    def add_resume(
        self,
        resume_text: str,
        resume_id: str | None = None,
        metadata: dict[str, Any] | None = None
    ) -> str:
        """
        Insert or update one resume.
        """
        record_id = resume_id or create_text_id(
            "resume",
            resume_text
        )

        record_metadata = clean_metadata({
            **(metadata or {}),
            "record_type": "resume",
            "embedding_model": self.model_type
        })

        self.resume_collection.upsert(
            ids=[record_id],
            embeddings=[self.embed(resume_text)],
            documents=[resume_text],
            metadatas=[record_metadata]
        )

        return record_id

    def add_job(
        self,
        jd_text: str,
        job_id: str | None = None,
        metadata: dict[str, Any] | None = None
    ) -> str:
        """
        Insert or update one job description.
        """
        record_id = job_id or create_text_id("job", jd_text)

        record_metadata = clean_metadata({
            **(metadata or {}),
            "record_type": "job_description",
            "embedding_model": self.model_type
        })

        self.job_collection.upsert(
            ids=[record_id],
            embeddings=[self.embed(jd_text)],
            documents=[jd_text],
            metadatas=[record_metadata]
        )

        return record_id

    def find_similar_jobs(
        self,
        resume_text: str,
        top_k: int = 5
    ) -> dict[str, Any]:
        """
        Find stored job descriptions most similar to a resume.
        """
        available = self.job_collection.count()

        if available == 0:
            return {
                "ids": [[]],
                "documents": [[]],
                "metadatas": [[]],
                "distances": [[]]
            }

        return self.job_collection.query(
            query_embeddings=[self.embed(resume_text)],
            n_results=min(top_k, available),
            include=["documents", "metadatas", "distances"]
        )

    def find_similar_resumes(
        self,
        jd_text: str,
        top_k: int = 5
    ) -> dict[str, Any]:
        """
        Find stored resumes most similar to a job description.
        """
        available = self.resume_collection.count()

        if available == 0:
            return {
                "ids": [[]],
                "documents": [[]],
                "metadatas": [[]],
                "distances": [[]]
            }

        return self.resume_collection.query(
            query_embeddings=[self.embed(jd_text)],
            n_results=min(top_k, available),
            include=["documents", "metadatas", "distances"]
        )

    def resume_count(self) -> int:
        return self.resume_collection.count()

    def job_count(self) -> int:
        return self.job_collection.count()

    def delete_resume(self, resume_id: str) -> None:
        self.resume_collection.delete(ids=[resume_id])

    def delete_job(self, job_id: str) -> None:
        self.job_collection.delete(ids=[job_id])